# install specifique php

- name: "epel activation"
  apt:
name: "epel-release"
state: present

- name: "remi repo activation"
  apt:
name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
state: present

- name: "install php70 packages"
  apt:
name: "php,php-mysql,php-xml,php-mbstring,php-mcrypt,php-gd,php-intl"
state: latest
enablerepo: "remi-php70"
  changed_when: yes
  notify: [ "apache restart" ]
