---
- hosts: local
  connection: local
  gather_facts: False
  vars:
   instance_type: t2.micro
   security_group: webservers_sg
   image: ami-06358f49b5839867c
   keypair: debian_jeremy
   region: ap-southeast-2b
   count: 1
  vars_files:
   - aws_keys.yml

  tasks:
  - name: Create a security group
    ec2_group:
        name: "{{ security_group }}"
        description: CentOS 7 -x86_64- - with Updates HVM-1901_01-AutogenByAWSMP-
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

  - name: Launch the new EC2 Instance
    ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true 
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: "{{count}}"
    register: ec2
