---
- name: "nginx installation"
  hosts: 192.168.88.136 
  tasks:
  - name: "update apt"
    apt:
      update_cache: yes

  - name: "install epel depot"
    apt:
      name: epel-release
      state: present

  - name: "update apt"
    apt:
      update_cache: yes

  - name: "install nginx package"
    apt:
      name: nginx
      state: present

  - name: "start nginx service"
    service:
      name: nginx
      state: started
      enabled: yes

  - name: "création dossier1"
    file:
      path: /usr/share/nginx/dossier_nginx_1/html
      state: directory

  - name: "création dossier2"
    file:
      path: /usr/share/nginx/dossier_nginx_2/html
      state: directory

  - name: "Copy index1.html"
    copy:
      src: index1.html
      dest: /usr/share/nginx/dossier_nginx_1/html/index1.html

