---
- name: Add a new user
  hosts: all
  vars:
   user: ajc
  tasks:

  - name: add new user
    user:
      name: "{{ user }}"
      shell: /bin/bash
      append: yes

  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ user}}"
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    
  - name : installation tools
    yum: name={{ item }} update_cache=yes state=latest
    with_items:
      - htop
      - git
      - zsh
      - sudo

  - name: set sudo right
    copy:
      src: /etc/sudoers.d/james
      dest: /etc/sudoers.d/james

  - name: config d'un template + interprétation de variable
    template:
      src: /etc/ansible/playbooks/template/sudoers.j2
      dest: /etc/sudoers.d/{{ user }}
