---
- name: Add a new user
  hosts: 192.168.88.136 
  vars:
   user: ajc
  tasks:

  - name: add new user
    user:
      name: james
      shell: /bin/bash
      append: yes

  - name: Set authorized key taken from file
    authorized_key:
      user: james
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

