---
# tasks file for mariadb

- name: "mariadb-server installation"
  apt:
    name:  "mariadb-server"
    state: "installed"
  become: yes

- name: "start mariadb service"
  service:
    name:  "mariadb"
    state: "started"
    enabled: yes
  become: ye


















